#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT_DIR}"

POLYXML_BIN="polyxml"
if [ -f "${ROOT_DIR}/../PolyXML/target/release/polyxml" ] && [ -f "${ROOT_DIR}/../PolyXML/target/debug/polyxml" ]; then
    if [ "${ROOT_DIR}/../PolyXML/target/release/polyxml" -nt "${ROOT_DIR}/../PolyXML/target/debug/polyxml" ]; then
        POLYXML_BIN="${ROOT_DIR}/../PolyXML/target/release/polyxml"
    else
        POLYXML_BIN="${ROOT_DIR}/../PolyXML/target/debug/polyxml"
    fi
elif [ -f "${ROOT_DIR}/../PolyXML/target/release/polyxml" ]; then
    POLYXML_BIN="${ROOT_DIR}/../PolyXML/target/release/polyxml"
elif [ -f "${ROOT_DIR}/../PolyXML/target/debug/polyxml" ]; then
    POLYXML_BIN="${ROOT_DIR}/../PolyXML/target/debug/polyxml"
fi

SCHEMA_PATH="schemas/uci/uci_entity_core.xsd"

echo "================================================================================"
echo "🛠️  PolyXML Code Generation Showcase (All 7 Target Languages)"
echo "   Schema: ${SCHEMA_PATH}"
echo "================================================================================"

echo -e "\n[1/7] 🦀 Generating Rust (Zero-Copy Borrowed Slices, Inherent Codecs & rkyv Wire Format)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang rust \
  --zero-copy \
  --codecs \
  --feature rkyv \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/rust

echo -e "\n[1b/7] 🧩 Generating Rust Topological Chunks (Bounded DAG Chunks)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang rust \
  --split-units \
  --chunk-size 4 \
  --zero-copy \
  --codecs \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/rust_chunked

echo -e "\n[2/7] 🐍 Generating Python (Dataclass Backend with Inherent Codecs)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang python \
  --backend dataclass \
  --codecs \
  --custom-header "# CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/python

echo -e "\n[2b/7] ⚡ Generating Python AOT (Ahead-of-Time Compiled PyO3 Native Extension)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang python \
  --backend aot \
  --package uci_aot \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/python_aot

if [ -f "${ROOT_DIR}/../PolyXML/.venv/bin/maturin" ] || command -v maturin &>/dev/null; then
    MATURIN_BIN="maturin"
    if [ -d "${ROOT_DIR}/../PolyXML/.venv" ]; then
        export VIRTUAL_ENV="${ROOT_DIR}/../PolyXML/.venv"
        MATURIN_BIN="${ROOT_DIR}/../PolyXML/.venv/bin/maturin"
    fi
    echo "  Compiling uci_aot PyO3 native extension via maturin develop --release..."
    (cd generated/python_aot && "${MATURIN_BIN}" develop --release) || true
fi

echo -e "\n[3/7] 🐹 Generating Go (Dual XML & JSON Struct Tags)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang go \
  --package uci \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/go

echo -e "\n[4/7] ⚡ Generating Modern C++20 (Header-Only Value Types & Concepts)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang cpp \
  --package "polyxml::generated" \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/cpp

echo -e "\n[5/7] ☕ Generating Java 22+ (Records & Sealed Interfaces)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang java \
  --package "com.enterprise.uci" \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/java

echo -e "\n[6/7] 🌐 Generating TypeScript 5+ (Typed Interfaces & Zod Validation)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang ts \
  --backend zod \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/typescript

echo -e "\n[7/7] 🔷 Generating C# 12 / .NET 8 (Primary Constructor Records & Native AOT Source Generator)..."
"${POLYXML_BIN}" generate "${SCHEMA_PATH}" \
  --lang csharp \
  --backend source-gen \
  --namespace "Enterprise.Uci" \
  --custom-header "// CLASSIFICATION: UNCLASSIFIED // NATO STANAG / UCI Telemetry // Generated by PolyXML." \
  --out generated/csharp

# Format Rust code
if command -v cargo &>/dev/null && [ -f examples/rust/Cargo.toml ]; then
    cargo fmt --manifest-path examples/rust/Cargo.toml || true
fi

echo -e "\n================================================================================"
echo "✅ Code generation complete across all 7 targets into generated/"
echo "   Alternatively, build all targets in one command using: polyxml build"
echo "================================================================================"
